# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/SF_MergeServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/SF_MergeServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/SF_MergeServer/CMakeFiles /home/SF_MergeServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/SF_MergeServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mergeServer

# Build rule for target.
mergeServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mergeServer
.PHONY : mergeServer

# fast build rule for target.
mergeServer/fast:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/build
.PHONY : mergeServer/fast

CThreadPool.o: CThreadPool.cpp.o

.PHONY : CThreadPool.o

# target to build an object file
CThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/CThreadPool.cpp.o
.PHONY : CThreadPool.cpp.o

CThreadPool.i: CThreadPool.cpp.i

.PHONY : CThreadPool.i

# target to preprocess a source file
CThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/CThreadPool.cpp.i
.PHONY : CThreadPool.cpp.i

CThreadPool.s: CThreadPool.cpp.s

.PHONY : CThreadPool.s

# target to generate assembly for a file
CThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/CThreadPool.cpp.s
.PHONY : CThreadPool.cpp.s

MergeRunable.o: MergeRunable.cpp.o

.PHONY : MergeRunable.o

# target to build an object file
MergeRunable.cpp.o:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/MergeRunable.cpp.o
.PHONY : MergeRunable.cpp.o

MergeRunable.i: MergeRunable.cpp.i

.PHONY : MergeRunable.i

# target to preprocess a source file
MergeRunable.cpp.i:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/MergeRunable.cpp.i
.PHONY : MergeRunable.cpp.i

MergeRunable.s: MergeRunable.cpp.s

.PHONY : MergeRunable.s

# target to generate assembly for a file
MergeRunable.cpp.s:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/MergeRunable.cpp.s
.PHONY : MergeRunable.cpp.s

mongoose.o: mongoose.c.o

.PHONY : mongoose.o

# target to build an object file
mongoose.c.o:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/mongoose.c.o
.PHONY : mongoose.c.o

mongoose.i: mongoose.c.i

.PHONY : mongoose.i

# target to preprocess a source file
mongoose.c.i:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/mongoose.c.i
.PHONY : mongoose.c.i

mongoose.s: mongoose.c.s

.PHONY : mongoose.s

# target to generate assembly for a file
mongoose.c.s:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/mongoose.c.s
.PHONY : mongoose.c.s

webserver.o: webserver.cpp.o

.PHONY : webserver.o

# target to build an object file
webserver.cpp.o:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/webserver.cpp.o
.PHONY : webserver.cpp.o

webserver.i: webserver.cpp.i

.PHONY : webserver.i

# target to preprocess a source file
webserver.cpp.i:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/webserver.cpp.i
.PHONY : webserver.cpp.i

webserver.s: webserver.cpp.s

.PHONY : webserver.s

# target to generate assembly for a file
webserver.cpp.s:
	$(MAKE) -f CMakeFiles/mergeServer.dir/build.make CMakeFiles/mergeServer.dir/webserver.cpp.s
.PHONY : webserver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mergeServer"
	@echo "... CThreadPool.o"
	@echo "... CThreadPool.i"
	@echo "... CThreadPool.s"
	@echo "... MergeRunable.o"
	@echo "... MergeRunable.i"
	@echo "... MergeRunable.s"
	@echo "... mongoose.o"
	@echo "... mongoose.i"
	@echo "... mongoose.s"
	@echo "... webserver.o"
	@echo "... webserver.i"
	@echo "... webserver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

